# ***EnsembleLearing(Classifier)- HARD/SOFT Task***

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/EDA Datasets csv/survey lung cancer.csv')

In [ ]:
data.head(10)

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0      M   69        1               2        2              1   
1      M   74        2               1        1              1   
2      F   59        1               1        1              2   
3      M   63        2               2        2              1   
4      F   63        1               2        1              1   
5      F   75        1               2        1              1   
6      M   52        2               1        1              1   
7      F   51        2               2        2              2   
8      F   68        2               1        2              1   
9      M   53        2               2        2              2   

   CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  \
0                1         2         1         2                  2         2   
1                2         2         2         1                  1         1   
2                1         2         1         2                  1         2   
3                1         1         1         1                  2         1   
4                1         1         1         2                  1         2   
5                2         2         2         2                  1         2   
6                1         2         1         2                  2         2   
7                1         2         2         1                  1         1   
8                1         2         1         1                  1         1   
9                2         1         2         1                  2         1   

   SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN LUNG_CANCER  
0                    2                      2           2         YES  
1                    2                      2           2         YES  
2                    2                      1           2          NO  
3                    1                      2           2          NO  
4                    2                      1           1          NO  
5                    2                      1           1         YES  
6                    2                      1           2         YES  
7                    2                      2           1         YES  
8                    1                      1           1          NO  
9                    1                      2           2         YES

In [ ]:
x = data.iloc[: , 1:15].values
y = data.iloc[: , -1].values

In [ ]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x,y, test_size = 0.3 , random_state=0)

In [ ]:
from sklearn.preprocessing import LabelEncoder , StandardScaler
le = LabelEncoder()
y_train = le.fit_transform(y_train)

In [ ]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

# ***DecisionTreeClassifier***

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(criterion='gini')
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
y_pred = dt.predict(x_test)

In [ ]:
y_pred

array([1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1])

In [ ]:
from sklearn.metrics import accuracy_score  
accuracy_score(y_pred,y_test)

0.8709677419354839

# ***RandomTreeClassifier***

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators= 10)
rf.fit(x_train,y_train)

RandomForestClassifier(n_estimators=10)

In [ ]:
y_pred_rf = rf.predict(x_test)

In [ ]:
y_pred_rf

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1])

In [ ]:
accuracy_score(y_test,y_pred_rf)

0.9139784946236559

# ***Create a voting classifier with HARD voting***



In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import VotingClassifier
vc_hard = VotingClassifier(
              estimators = [('dtc',  DecisionTreeClassifier(random_state=0)),
                            ('lr', LogisticRegression()),
                            ('rfc', RandomForestClassifier())],
                           voting='hard')


In [ ]:
vc_hard.fit(x_train,y_train)

VotingClassifier(estimators=[('dtc', DecisionTreeClassifier(random_state=0)),
                             ('lr', LogisticRegression()),
                             ('rfc', RandomForestClassifier())])

In [ ]:
y_pred_vch = vc_hard.predict(x_test)

In [ ]:
y_pred_vch

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1])

# ***Create a voting classifier with SOFT voting***

In [ ]:
vc_soft = VotingClassifier(
    estimators = [('dtc', DecisionTreeClassifier(random_state=0)),
                  ('lr', LogisticRegression()),
                  ('rfc', RandomForestClassifier())], 
                     voting='soft')

In [ ]:
vc_soft.fit(x_train,y_train)

VotingClassifier(estimators=[('dtc', DecisionTreeClassifier(random_state=0)),
                             ('lr', LogisticRegression()),
                             ('rfc', RandomForestClassifier())],
                 voting='soft')

In [ ]:
y_pred_vcs = vc_soft.predict(x_test)

In [ ]:
y_pred_vcs

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1])

In [ ]:
# Finding HARD and SOFT accuracy
accuracy_score(y_test, y_pred_vch),accuracy_score(y_test, y_pred_vcs)

(0.8817204301075269, 0.8817204301075269)